### ISSUE TITLE
Stuck on loading then crash

### ISSUE THREAD

**Issue by Moa-Kikuchi** [NimaKhajehpour/GuessThatPokemon#20]
On app version 2.1, after pressing the start game button and selecting English and selecting any of the gens, the game will get stuck loading and eventually crash the app.

I'm using a stock Pixel 7, latest version of Android 13. ARM64 only device. Downloaded from FDroid. Have tried uninstalling and reinstalling and no fix.

**Comment by Moa-Kikuchi** [comment]
After checking, it's working this morning. Ignore this issue.

**Comment by Moa-Kikuchi** [comment]
Just glad it's working! I'm enjoying it so far!

**Comment by NimaKhajehpour** [comment]
thanks for using my app and im glad you are enjoying it
