### ISSUE TITLE
Limit to specific versions

### ISSUE THREAD

**Issue by supermamie** [NimaKhajehpour/GuessThatPokemon#3]
As I'm old and still in a world with 250 Pokémons, is it possible to add a setting to limit the version used ?

**Comment by NimaKhajehpour** [comment]
Hey! Thanks for using my app. ❤️ I hope you have a great time using the app and playing the game. At the moment there is no feature for choosing between versions of pokemon. But i could add the feature in the next update so that it is easier and more friendly with all kinds of pokemon lovers 😊

**Comment by MarcSN311** [comment]
I came here to ask for the same thing! This would be a great feature.

**Comment by NimaKhajehpour** [comment]
@MarcSN311 ohey there thanks for using the app. At the moment i am busy with my university as i am a student and could not work on updates. But i can hopefully work on the updates in the next 2 or 3 weeks and it will be accessible for the users. Thanks for the feedback and your patience ❤️
