### ISSUE TITLE
Add a skip button

### ISSUE THREAD

**Issue by RyuKurisu** [NimaKhajehpour/GuessThatPokemon#8]
Sometimes I'm absolutely fabled by the Pokémon shown, so a skip button would be very welcome to learn about that Pokémon.

**Comment by NimaKhajehpour** [comment]
Yeah i guess that could be a good feature to add. Hopefully i have enough time to add features this week and push the updates on fdroid. Thanks for using the app and i hope you enjoy using it ❤️
